INSERT INTO departamentos (id,nombre) VALUES (5,'ANTIOQUIA');
INSERT INTO departamentos (id,nombre) VALUES (8,'ATLANTICO');
INSERT INTO departamentos (id,nombre) VALUES (11,'BOGOTA');
INSERT INTO departamentos (id,nombre) VALUES (13,'BOLIVAR');
INSERT INTO departamentos (id,nombre) VALUES (15,'BOYACA');
INSERT INTO departamentos (id,nombre) VALUES (17,'CALDAS');
INSERT INTO departamentos (id,nombre) VALUES (18,'CAQUETA');
INSERT INTO departamentos (id,nombre) VALUES (19,'CAUCA');
INSERT INTO departamentos (id,nombre) VALUES (20,'CESAR');
INSERT INTO departamentos (id,nombre) VALUES (23,'CORDOBA');
INSERT INTO departamentos (id,nombre) VALUES (25,'CUNDINAMARCA');
INSERT INTO departamentos (id,nombre) VALUES (27,'CHOCO');
INSERT INTO departamentos (id,nombre) VALUES (41,'HUILA');
INSERT INTO departamentos (id,nombre) VALUES (44,'LA GUAJIRA');
INSERT INTO departamentos (id,nombre) VALUES (47,'MAGDALENA');
INSERT INTO departamentos (id,nombre) VALUES (50,'META');
INSERT INTO departamentos (id,nombre) VALUES (52,'NARIÑO');
INSERT INTO departamentos (id,nombre) VALUES (54,'N. DE SANTANDER');
INSERT INTO departamentos (id,nombre) VALUES (63,'QUINDIO');
INSERT INTO departamentos (id,nombre) VALUES (66,'RISARALDA');
INSERT INTO departamentos (id,nombre) VALUES (68,'SANTANDER');
INSERT INTO departamentos (id,nombre) VALUES (70,'SUCRE');
INSERT INTO departamentos (id,nombre) VALUES (73,'TOLIMA');
INSERT INTO departamentos (id,nombre) VALUES (76,'VALLE DEL CAUCA');
INSERT INTO departamentos (id,nombre) VALUES (81,'ARAUCA');
INSERT INTO departamentos (id,nombre) VALUES (85,'CASANARE');
INSERT INTO departamentos (id,nombre) VALUES (86,'PUTUMAYO');
INSERT INTO departamentos (id,nombre) VALUES (88,'SAN ANDRES');
INSERT INTO departamentos (id,nombre) VALUES (91,'AMAZONAS');
INSERT INTO departamentos (id,nombre) VALUES (94,'GUAINIA');
INSERT INTO departamentos (id,nombre) VALUES (95,'GUAVIARE');
INSERT INTO departamentos (id,nombre) VALUES (97,'VAUPES');
INSERT INTO departamentos (id,nombre) VALUES (99,'VICHADA');