INSERT INTO municipios (departamento,nombre) VALUES (5,'MEDELLIN');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ABEJORRAL');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ABRIAQUI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ALEJANDRIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'AMAGA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'AMALFI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ANDES');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ANGELOPOLIS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ANGOSTURA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ANORI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SANTAFE DE ANTIOQUIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ANZA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'APARTADO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ARBOLETES');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ARGELIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ARMENIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BARBOSA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BELMIRA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BELLO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BETANIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BETULIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CIUDAD BOLIVAR');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BRICEÑO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'BURITICA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CACERES');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAICEDO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CALDAS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAMPAMENTO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAÑASGORDAS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CARACOLI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CARAMANTA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAREPA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'EL CARMEN DE VIBORAL');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAROLINA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CAUCASIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CHIGORODO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CISNEROS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'COCORNA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CONCEPCION');
INSERT INTO municipios (departamento,nombre) VALUES (5,'CONCORDIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'COPACABANA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'DABEIBA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'DONMATíAS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'EBEJICO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'EL BAGRE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ENTRERRIOS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ENVIGADO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'FREDONIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'FRONTINO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GIRALDO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GIRARDOTA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GOMEZ PLATA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GRANADA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GUADALUPE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GUARNE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'GUATAPE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'HELICONIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'HISPANIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ITAGUI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ITUANGO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'JARDIN');
INSERT INTO municipios (departamento,nombre) VALUES (5,'JERICO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'LA CEJA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'LA ESTRELLA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'LA PINTADA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'LA UNION');
INSERT INTO municipios (departamento,nombre) VALUES (5,'LIBORINA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'MACEO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'MARINILLA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'MONTEBELLO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'MURINDO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'MUTATA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'NARIÑO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'NECOCLI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'NECHI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'OLAYA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PEÐOL');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PEQUE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PUEBLORRICO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PUERTO BERRIO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PUERTO NARE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'PUERTO TRIUNFO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'REMEDIOS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'RETIRO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'RIONEGRO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SABANALARGA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SABANETA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SALGAR');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN ANDRES DE CUERQUIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN CARLOS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN FRANCISCO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN JERONIMO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN JOSE DE LA MONTAÑA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN JUAN DE URABA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN LUIS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN PEDRO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN PEDRO DE URABA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN RAFAEL');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN ROQUE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SAN VICENTE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SANTA BARBARA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SANTA ROSA DE OSOS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SANTO DOMINGO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'EL SANTUARIO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SEGOVIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SONSON');
INSERT INTO municipios (departamento,nombre) VALUES (5,'SOPETRAN');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TAMESIS');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TARAZA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TARSO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TITIRIBI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TOLEDO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'TURBO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'URAMITA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'URRAO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'VALDIVIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'VALPARAISO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'VEGACHI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'VENECIA');
INSERT INTO municipios (departamento,nombre) VALUES (5,'VIGIA DEL FUERTE');
INSERT INTO municipios (departamento,nombre) VALUES (5,'YALI');
INSERT INTO municipios (departamento,nombre) VALUES (5,'YARUMAL');
INSERT INTO municipios (departamento,nombre) VALUES (5,'YOLOMBO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'YONDO');
INSERT INTO municipios (departamento,nombre) VALUES (5,'ZARAGOZA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'BARRANQUILLA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'BARANOA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'CAMPO DE LA CRUZ');
INSERT INTO municipios (departamento,nombre) VALUES (8,'CANDELARIA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'GALAPA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'JUAN DE ACOSTA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'LURUACO');
INSERT INTO municipios (departamento,nombre) VALUES (8,'MALAMBO');
INSERT INTO municipios (departamento,nombre) VALUES (8,'MANATI');
INSERT INTO municipios (departamento,nombre) VALUES (8,'PALMAR DE VARELA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'PIOJO');
INSERT INTO municipios (departamento,nombre) VALUES (8,'POLONUEVO');
INSERT INTO municipios (departamento,nombre) VALUES (8,'PONEDERA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'PUERTO COLOMBIA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'REPELON');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SABANAGRANDE');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SABANALARGA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SANTA LUCIA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SANTO TOMAS');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SOLEDAD');
INSERT INTO municipios (departamento,nombre) VALUES (8,'SUAN');
INSERT INTO municipios (departamento,nombre) VALUES (8,'TUBARA');
INSERT INTO municipios (departamento,nombre) VALUES (8,'USIACURI');
INSERT INTO municipios (departamento,nombre) VALUES (11,'BOGOTA, D.C.');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CARTAGENA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ACHI');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ALTOS DEL ROSARIO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ARENAL');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ARJONA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ARROYOHONDO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'BARRANCO DE LOBA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CALAMAR');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CANTAGALLO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CICUCO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CORDOBA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'CLEMENCIA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'EL CARMEN DE BOLIVAR');
INSERT INTO municipios (departamento,nombre) VALUES (13,'EL GUAMO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'EL PEÑON');
INSERT INTO municipios (departamento,nombre) VALUES (13,'HATILLO DE LOBA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MAGANGUE');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MAHATES');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MARGARITA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MARIA LA BAJA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MONTECRISTO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MOMPOS');
INSERT INTO municipios (departamento,nombre) VALUES (13,'MORALES');
INSERT INTO municipios (departamento,nombre) VALUES (13,'NOROSI');
INSERT INTO municipios (departamento,nombre) VALUES (13,'PINILLOS');
INSERT INTO municipios (departamento,nombre) VALUES (13,'REGIDOR');
INSERT INTO municipios (departamento,nombre) VALUES (13,'RIO VIEJO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN CRISTOBAL');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN ESTANISLAO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN FERNANDO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN JACINTO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN JACINTO DEL CAUCA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN JUAN NEPOMUCENO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN MARTIN DE LOBA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SAN PABLO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SANTA CATALINA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SANTA ROSA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SANTA ROSA DEL SUR');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SIMITI');
INSERT INTO municipios (departamento,nombre) VALUES (13,'SOPLAVIENTO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'TALAIGUA NUEVO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'TIQUISIO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'TURBACO');
INSERT INTO municipios (departamento,nombre) VALUES (13,'TURBANA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'VILLANUEVA');
INSERT INTO municipios (departamento,nombre) VALUES (13,'ZAMBRANO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TUNJA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'ALMEIDA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'AQUITANIA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'ARCABUCO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BELEN');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BERBEO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BETEITIVA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BOAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PUERTO BOYACA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BRICEÑO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BUENAVISTA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'BUSBANZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CALDAS');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CAMPOHERMOSO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CERINZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHINAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHIQUINQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHISCAS');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHITARAQUE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHIVATA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CIENEGA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'COMBITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'COPER');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CORRALES');
INSERT INTO municipios (departamento,nombre) VALUES (15,'COVARACHIA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CUBARA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CUCAITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CUITIVA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHIQUIZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'CHIVOR');
INSERT INTO municipios (departamento,nombre) VALUES (15,'DUITAMA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'EL COCUY');
INSERT INTO municipios (departamento,nombre) VALUES (15,'EL ESPINO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'FIRAVITOBA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'FLORESTA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GACHANTIVA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GAMEZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GARAGOA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GUACAMAYAS');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GUATEQUE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GUAYATA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'GsICAN');
INSERT INTO municipios (departamento,nombre) VALUES (15,'IZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'JENESANO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'JERICO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'LABRANZAGRANDE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'LA CAPILLA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'LA VICTORIA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'LA UVITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'VILLA DE LEYVA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MACANAL');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MARIPI');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MIRAFLORES');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MONGUA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MONGUI');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MONIQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MOTAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'MUZO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'NOBSA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'NUEVO COLON');
INSERT INTO municipios (departamento,nombre) VALUES (15,'OICATA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'OTANCHE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PACHAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAEZ');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAIPA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAJARITO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PANQUEBA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAUNA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAYA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PAZ DE RIO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PESCA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PISBA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'PUERTO BOYACA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'QUIPAMA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'RAMIRIQUI');
INSERT INTO municipios (departamento,nombre) VALUES (15,'RAQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'RONDON');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SABOYA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SACHICA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAMACA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN EDUARDO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN JOSE DE PARE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN LUIS DE GACENO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN MATEO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN MIGUEL DE SEMA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SAN PABLO DE BORBUR');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SANTANA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SANTA MARIA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SANTA ROSA DE VITERBO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SANTA SOFIA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SATIVANORTE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SATIVASUR');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SIACHOQUE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOATA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOCOTA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOCHA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOGAMOSO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOMONDOCO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SORA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SOTAQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SORACA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SUSACON');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SUTAMARCHAN');
INSERT INTO municipios (departamento,nombre) VALUES (15,'SUTATENZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TASCO');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TENZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TIBANA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TIBASOSA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TINJACA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TIPACOQUE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TOCA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TOGsI');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TOPAGA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TOTA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TUNUNGUA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TURMEQUE');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TUTA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'TUTAZA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'UMBITA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'VENTAQUEMADA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'VIRACACHA');
INSERT INTO municipios (departamento,nombre) VALUES (15,'ZETAQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'MANIZALES');
INSERT INTO municipios (departamento,nombre) VALUES (17,'AGUADAS');
INSERT INTO municipios (departamento,nombre) VALUES (17,'ANSERMA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'ARANZAZU');
INSERT INTO municipios (departamento,nombre) VALUES (17,'BELALCAZAR');
INSERT INTO municipios (departamento,nombre) VALUES (17,'CHINCHINA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'FILADELFIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'LA DORADA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'LA MERCED');
INSERT INTO municipios (departamento,nombre) VALUES (17,'MANZANARES');
INSERT INTO municipios (departamento,nombre) VALUES (17,'MARMATO');
INSERT INTO municipios (departamento,nombre) VALUES (17,'MARQUETALIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'MARULANDA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'NEIRA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'NORCASIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'PACORA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'PALESTINA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'PENSILVANIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'RIOSUCIO');
INSERT INTO municipios (departamento,nombre) VALUES (17,'RISARALDA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'SALAMINA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'SAMANA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'SAN JOSE');
INSERT INTO municipios (departamento,nombre) VALUES (17,'SUPIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'VICTORIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'VILLAMARIA');
INSERT INTO municipios (departamento,nombre) VALUES (17,'VITERBO');
INSERT INTO municipios (departamento,nombre) VALUES (18,'FLORENCIA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'ALBANIA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'BELEN DE LOS ANDAQUIES');
INSERT INTO municipios (departamento,nombre) VALUES (18,'CARTAGENA DEL CHAIRA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'CURILLO');
INSERT INTO municipios (departamento,nombre) VALUES (18,'EL DONCELLO');
INSERT INTO municipios (departamento,nombre) VALUES (18,'EL PAUJIL');
INSERT INTO municipios (departamento,nombre) VALUES (18,'LA MONTAÑITA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'MILAN');
INSERT INTO municipios (departamento,nombre) VALUES (18,'MORELIA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'PUERTO RICO');
INSERT INTO municipios (departamento,nombre) VALUES (18,'SAN JOSE DEL FRAGUA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'SAN VICENTE DEL CAGUAN');
INSERT INTO municipios (departamento,nombre) VALUES (18,'SOLANO');
INSERT INTO municipios (departamento,nombre) VALUES (18,'SOLITA');
INSERT INTO municipios (departamento,nombre) VALUES (18,'VALPARAISO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'POPAYAN');
INSERT INTO municipios (departamento,nombre) VALUES (19,'ALMAGUER');
INSERT INTO municipios (departamento,nombre) VALUES (19,'ARGELIA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'BALBOA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'BOLIVAR');
INSERT INTO municipios (departamento,nombre) VALUES (19,'BUENOS AIRES');
INSERT INTO municipios (departamento,nombre) VALUES (19,'CAJIBIO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'CALDONO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'CALOTO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'CORINTO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'EL TAMBO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'FLORENCIA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'GUACHENE');
INSERT INTO municipios (departamento,nombre) VALUES (19,'GUAPI');
INSERT INTO municipios (departamento,nombre) VALUES (19,'INZA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'JAMBALO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'LA SIERRA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'LA VEGA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'LOPEZ');
INSERT INTO municipios (departamento,nombre) VALUES (19,'MERCADERES');
INSERT INTO municipios (departamento,nombre) VALUES (19,'MIRANDA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'MORALES');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PADILLA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PAEZ');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PATIA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PIAMONTE');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PIENDAMO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PUERTO TEJADA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'PURACE');
INSERT INTO municipios (departamento,nombre) VALUES (19,'ROSAS');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SAN SEBASTIAN');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SANTANDER DE QUILICHAO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SANTA ROSA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SILVIA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SOTARA');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SUAREZ');
INSERT INTO municipios (departamento,nombre) VALUES (19,'SUCRE');
INSERT INTO municipios (departamento,nombre) VALUES (19,'TIMBIO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'TIMBIQUI');
INSERT INTO municipios (departamento,nombre) VALUES (19,'TORIBIO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'TOTORO');
INSERT INTO municipios (departamento,nombre) VALUES (19,'VILLA RICA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'VALLEDUPAR');
INSERT INTO municipios (departamento,nombre) VALUES (20,'AGUACHICA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'AGUSTIN CODAZZI');
INSERT INTO municipios (departamento,nombre) VALUES (20,'ASTREA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'BECERRIL');
INSERT INTO municipios (departamento,nombre) VALUES (20,'BOSCONIA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'CHIMICHAGUA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'CHIRIGUANA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'CURUMANI');
INSERT INTO municipios (departamento,nombre) VALUES (20,'EL COPEY');
INSERT INTO municipios (departamento,nombre) VALUES (20,'EL PASO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'GAMARRA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'GONZALEZ');
INSERT INTO municipios (departamento,nombre) VALUES (20,'LA GLORIA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'LA JAGUA DE IBIRICO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'MANAURE');
INSERT INTO municipios (departamento,nombre) VALUES (20,'PAILITAS');
INSERT INTO municipios (departamento,nombre) VALUES (20,'PELAYA');
INSERT INTO municipios (departamento,nombre) VALUES (20,'PUEBLO BELLO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'RIO DE ORO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'LA PAZ');
INSERT INTO municipios (departamento,nombre) VALUES (20,'SAN ALBERTO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'SAN DIEGO');
INSERT INTO municipios (departamento,nombre) VALUES (20,'SAN MARTIN');
INSERT INTO municipios (departamento,nombre) VALUES (20,'TAMALAMEQUE');
INSERT INTO municipios (departamento,nombre) VALUES (23,'MONTERIA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'AYAPEL');
INSERT INTO municipios (departamento,nombre) VALUES (23,'BUENAVISTA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'CANALETE');
INSERT INTO municipios (departamento,nombre) VALUES (23,'CERETE');
INSERT INTO municipios (departamento,nombre) VALUES (23,'CHIMA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'CHINU');
INSERT INTO municipios (departamento,nombre) VALUES (23,'CIENAGA DE ORO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'COTORRA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'LA APARTADA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'LORICA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'LOS CORDOBAS');
INSERT INTO municipios (departamento,nombre) VALUES (23,'MOMIL');
INSERT INTO municipios (departamento,nombre) VALUES (23,'MONTELIBANO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'MOÑITOS');
INSERT INTO municipios (departamento,nombre) VALUES (23,'PLANETA RICA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'PUEBLO NUEVO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'PUERTO ESCONDIDO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'PUERTO LIBERTADOR');
INSERT INTO municipios (departamento,nombre) VALUES (23,'PURISIMA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAHAGUN');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAN ANDRES SOTAVENTO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAN ANTERO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAN BERNARDO DEL VIENTO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAN CARLOS');
INSERT INTO municipios (departamento,nombre) VALUES (23,'SAN PELAYO');
INSERT INTO municipios (departamento,nombre) VALUES (23,'TIERRALTA');
INSERT INTO municipios (departamento,nombre) VALUES (23,'VALENCIA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'AGUA DE DIOS');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ALBAN');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ANAPOIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ANOLAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ARBELAEZ');
INSERT INTO municipios (departamento,nombre) VALUES (25,'BELTRAN');
INSERT INTO municipios (departamento,nombre) VALUES (25,'BITUIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'BOJACA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CABRERA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CACHIPAY');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CAJICA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CAPARRAPI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CAQUEZA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CARMEN DE CARUPA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CHAGUANI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CHIA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CHIPAQUE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CHOACHI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CHOCONTA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'COGUA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'COTA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'CUCUNUBA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'EL COLEGIO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'EL PEÑON');
INSERT INTO municipios (departamento,nombre) VALUES (25,'EL ROSAL');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FACATATIVA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FOMEQUE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FOSCA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FUNZA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FUQUENE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'FUSAGASUGA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GACHALA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GACHANCIPA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GACHETA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GAMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GIRARDOT');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GRANADA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUACHETA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUADUAS');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUASCA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUATAQUI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUATAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUAYABAL DE SIQUIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUAYABETAL');
INSERT INTO municipios (departamento,nombre) VALUES (25,'GUTIERREZ');
INSERT INTO municipios (departamento,nombre) VALUES (25,'JERUSALEN');
INSERT INTO municipios (departamento,nombre) VALUES (25,'JUNIN');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LA CALERA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LA MESA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LA PALMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LA PEÑA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LA VEGA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'LENGUAZAQUE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'MACHETA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'MADRID');
INSERT INTO municipios (departamento,nombre) VALUES (25,'MANTA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'MEDINA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'MOSQUERA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'NARIÑO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'NEMOCON');
INSERT INTO municipios (departamento,nombre) VALUES (25,'NILO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'NIMAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'NOCAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VENECIA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PACHO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PAIME');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PANDI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PARATEBUENO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PASCA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PUERTO SALGAR');
INSERT INTO municipios (departamento,nombre) VALUES (25,'PULI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'QUEBRADANEGRA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'QUETAME');
INSERT INTO municipios (departamento,nombre) VALUES (25,'QUIPILE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'APULO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'RICAURTE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SAN ANTONIO DEL TEQUENDAMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SAN BERNARDO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SAN CAYETANO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SAN FRANCISCO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SAN JUAN DE RIO SECO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SASAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SESQUILE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SIBATE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SILVANIA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SIMIJACA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SOACHA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SOPO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SUBACHOQUE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SUESCA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SUPATA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SUSA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'SUTATAUSA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TABIO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TAUSA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TENA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TENJO');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TIBACUY');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TIBIRITA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TOCAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TOCANCIPA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'TOPAIPI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'UBALA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'UBAQUE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VILLA DE SAN DIEGO DE UBATE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'UNE');
INSERT INTO municipios (departamento,nombre) VALUES (25,'UTICA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VERGARA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VIANI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VILLAGOMEZ');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VILLAPINZON');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VILLETA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'VIOTA');
INSERT INTO municipios (departamento,nombre) VALUES (25,'YACOPI');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ZIPACON');
INSERT INTO municipios (departamento,nombre) VALUES (25,'ZIPAQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (27,'QUIBDO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'ACANDI');
INSERT INTO municipios (departamento,nombre) VALUES (27,'ALTO BAUDO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'ATRATO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'BAGADO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'BAHIA SOLANO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'BAJO BAUDO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'BOJAYA');
INSERT INTO municipios (departamento,nombre) VALUES (27,'EL CANTON DEL SAN PABLO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'CARMEN DEL DARIEN');
INSERT INTO municipios (departamento,nombre) VALUES (27,'CERTEGUI');
INSERT INTO municipios (departamento,nombre) VALUES (27,'CONDOTO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'EL CARMEN DE ATRATO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'EL LITORAL DEL SAN JUAN');
INSERT INTO municipios (departamento,nombre) VALUES (27,'ISTMINA');
INSERT INTO municipios (departamento,nombre) VALUES (27,'JURADO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'LLORO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'MEDIO ATRATO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'MEDIO BAUDO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'MEDIO SAN JUAN');
INSERT INTO municipios (departamento,nombre) VALUES (27,'NOVITA');
INSERT INTO municipios (departamento,nombre) VALUES (27,'NUQUI');
INSERT INTO municipios (departamento,nombre) VALUES (27,'RIO IRO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'RIO QUITO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'RIOSUCIO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'SAN JOSE DEL PALMAR');
INSERT INTO municipios (departamento,nombre) VALUES (27,'SIPI');
INSERT INTO municipios (departamento,nombre) VALUES (27,'TADO');
INSERT INTO municipios (departamento,nombre) VALUES (27,'UNGUIA');
INSERT INTO municipios (departamento,nombre) VALUES (27,'UNION PANAMERICANA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'NEIVA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'ACEVEDO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'AGRADO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'AIPE');
INSERT INTO municipios (departamento,nombre) VALUES (41,'ALGECIRAS');
INSERT INTO municipios (departamento,nombre) VALUES (41,'ALTAMIRA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'BARAYA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'CAMPOALEGRE');
INSERT INTO municipios (departamento,nombre) VALUES (41,'COLOMBIA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'ELIAS');
INSERT INTO municipios (departamento,nombre) VALUES (41,'GARZON');
INSERT INTO municipios (departamento,nombre) VALUES (41,'GIGANTE');
INSERT INTO municipios (departamento,nombre) VALUES (41,'GUADALUPE');
INSERT INTO municipios (departamento,nombre) VALUES (41,'HOBO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'IQUIRA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'ISNOS');
INSERT INTO municipios (departamento,nombre) VALUES (41,'LA ARGENTINA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'LA PLATA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'NATAGA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'OPORAPA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'PAICOL');
INSERT INTO municipios (departamento,nombre) VALUES (41,'PALERMO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'PALESTINA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'PITAL');
INSERT INTO municipios (departamento,nombre) VALUES (41,'PITALITO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'RIVERA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'SALADOBLANCO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'SAN AGUSTIN');
INSERT INTO municipios (departamento,nombre) VALUES (41,'SANTA MARIA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'SUAZA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'TARQUI');
INSERT INTO municipios (departamento,nombre) VALUES (41,'TESALIA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'TELLO');
INSERT INTO municipios (departamento,nombre) VALUES (41,'TERUEL');
INSERT INTO municipios (departamento,nombre) VALUES (41,'TIMANA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'VILLAVIEJA');
INSERT INTO municipios (departamento,nombre) VALUES (41,'YAGUARA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'RIOHACHA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'ALBANIA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'BARRANCAS');
INSERT INTO municipios (departamento,nombre) VALUES (44,'DIBULLA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'DISTRACCION');
INSERT INTO municipios (departamento,nombre) VALUES (44,'EL MOLINO');
INSERT INTO municipios (departamento,nombre) VALUES (44,'FONSECA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'HATONUEVO');
INSERT INTO municipios (departamento,nombre) VALUES (44,'LA JAGUA DEL PILAR');
INSERT INTO municipios (departamento,nombre) VALUES (44,'MAICAO');
INSERT INTO municipios (departamento,nombre) VALUES (44,'MANAURE');
INSERT INTO municipios (departamento,nombre) VALUES (44,'SAN JUAN DEL CESAR');
INSERT INTO municipios (departamento,nombre) VALUES (44,'URIBIA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'URUMITA');
INSERT INTO municipios (departamento,nombre) VALUES (44,'VILLANUEVA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SANTA MARTA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'ALGARROBO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'ARACATACA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'ARIGUANI');
INSERT INTO municipios (departamento,nombre) VALUES (47,'CERRO SAN ANTONIO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'CHIBOLO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'CIENAGA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'CONCORDIA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'EL BANCO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'EL PIÑON');
INSERT INTO municipios (departamento,nombre) VALUES (47,'EL RETEN');
INSERT INTO municipios (departamento,nombre) VALUES (47,'FUNDACION');
INSERT INTO municipios (departamento,nombre) VALUES (47,'GUAMAL');
INSERT INTO municipios (departamento,nombre) VALUES (47,'NUEVA GRANADA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'PEDRAZA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'PIJIÑO DEL CARMEN');
INSERT INTO municipios (departamento,nombre) VALUES (47,'PIVIJAY');
INSERT INTO municipios (departamento,nombre) VALUES (47,'PLATO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'PUEBLOVIEJO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'REMOLINO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SABANAS DE SAN ANGEL');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SALAMINA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SAN SEBASTIAN DE BUENAVISTA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SAN ZENON');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SANTA ANA');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SANTA BARBARA DE PINTO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'SITIONUEVO');
INSERT INTO municipios (departamento,nombre) VALUES (47,'TENERIFE');
INSERT INTO municipios (departamento,nombre) VALUES (47,'ZAPAYAN');
INSERT INTO municipios (departamento,nombre) VALUES (47,'ZONA BANANERA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'VILLAVICENCIO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'ACACIAS');
INSERT INTO municipios (departamento,nombre) VALUES (50,'BARRANCA DE UPIA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'CABUYARO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'CASTILLA LA NUEVA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'CUBARRAL');
INSERT INTO municipios (departamento,nombre) VALUES (50,'CUMARAL');
INSERT INTO municipios (departamento,nombre) VALUES (50,'EL CALVARIO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'EL CASTILLO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'EL DORADO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'FUENTE DE ORO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'GRANADA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'GUAMAL');
INSERT INTO municipios (departamento,nombre) VALUES (50,'MAPIRIPAN');
INSERT INTO municipios (departamento,nombre) VALUES (50,'MESETAS');
INSERT INTO municipios (departamento,nombre) VALUES (50,'LA MACARENA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'URIBE');
INSERT INTO municipios (departamento,nombre) VALUES (50,'LEJANIAS');
INSERT INTO municipios (departamento,nombre) VALUES (50,'PUERTO CONCORDIA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'PUERTO GAITAN');
INSERT INTO municipios (departamento,nombre) VALUES (50,'PUERTO LOPEZ');
INSERT INTO municipios (departamento,nombre) VALUES (50,'PUERTO LLERAS');
INSERT INTO municipios (departamento,nombre) VALUES (50,'PUERTO RICO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'RESTREPO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'SAN CARLOS DE GUAROA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'SAN JUAN DE ARAMA');
INSERT INTO municipios (departamento,nombre) VALUES (50,'SAN JUANITO');
INSERT INTO municipios (departamento,nombre) VALUES (50,'SAN MARTIN');
INSERT INTO municipios (departamento,nombre) VALUES (50,'VISTAHERMOSA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'PASTO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ALBAN');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ALDANA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ANCUYA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ARBOLEDA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'BARBACOAS');
INSERT INTO municipios (departamento,nombre) VALUES (52,'BELEN');
INSERT INTO municipios (departamento,nombre) VALUES (52,'BUESACO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'COLON');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CONSACA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CONTADERO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CORDOBA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CUASPUD');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CUMBAL');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CUMBITARA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'CHACHAGsI');
INSERT INTO municipios (departamento,nombre) VALUES (52,'EL CHARCO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'EL PEÑOL');
INSERT INTO municipios (departamento,nombre) VALUES (52,'EL ROSARIO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'EL TABLON DE GOMEZ');
INSERT INTO municipios (departamento,nombre) VALUES (52,'EL TAMBO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'FUNES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'GUACHUCAL');
INSERT INTO municipios (departamento,nombre) VALUES (52,'GUAITARILLA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'GUALMATAN');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ILES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'IMUES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'IPIALES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LA CRUZ');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LA FLORIDA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LA LLANADA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LA TOLA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LA UNION');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LEIVA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LINARES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'LOS ANDES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'MAGsI');
INSERT INTO municipios (departamento,nombre) VALUES (52,'MALLAMA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'MOSQUERA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'NARIÑO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'OLAYA HERRERA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'OSPINA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'FRANCISCO PIZARRO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'POLICARPA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'POTOSI');
INSERT INTO municipios (departamento,nombre) VALUES (52,'PROVIDENCIA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'PUERRES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'PUPIALES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'RICAURTE');
INSERT INTO municipios (departamento,nombre) VALUES (52,'ROBERTO PAYAN');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAMANIEGO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SANDONA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAN BERNARDO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAN LORENZO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAN PABLO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAN PEDRO DE CARTAGO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SANTA BARBARA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SANTACRUZ');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAPUYES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'TAMINANGO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'TANGUA');
INSERT INTO municipios (departamento,nombre) VALUES (52,'SAN ANDRES DE TUMACO');
INSERT INTO municipios (departamento,nombre) VALUES (52,'TUQUERRES');
INSERT INTO municipios (departamento,nombre) VALUES (52,'YACUANQUER');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CUCUTA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'ABREGO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'ARBOLEDAS');
INSERT INTO municipios (departamento,nombre) VALUES (54,'BOCHALEMA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'BUCARASICA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CACOTA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CACHIRA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CHINACOTA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CHITAGA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CONVENCION');
INSERT INTO municipios (departamento,nombre) VALUES (54,'CUCUTILLA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'DURANIA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'EL CARMEN');
INSERT INTO municipios (departamento,nombre) VALUES (54,'EL TARRA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'EL ZULIA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'GRAMALOTE');
INSERT INTO municipios (departamento,nombre) VALUES (54,'HACARI');
INSERT INTO municipios (departamento,nombre) VALUES (54,'HERRAN');
INSERT INTO municipios (departamento,nombre) VALUES (54,'LABATECA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'LA ESPERANZA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'LA PLAYA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'LOS PATIOS');
INSERT INTO municipios (departamento,nombre) VALUES (54,'LOURDES');
INSERT INTO municipios (departamento,nombre) VALUES (54,'MUTISCUA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'OCAÑA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'PAMPLONA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'PAMPLONITA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'PUERTO SANTANDER');
INSERT INTO municipios (departamento,nombre) VALUES (54,'RAGONVALIA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SALAZAR');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SAN CALIXTO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SAN CAYETANO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SANTIAGO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SARDINATA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'SILOS');
INSERT INTO municipios (departamento,nombre) VALUES (54,'TEORAMA');
INSERT INTO municipios (departamento,nombre) VALUES (54,'TIBU');
INSERT INTO municipios (departamento,nombre) VALUES (54,'TOLEDO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'VILLA CARO');
INSERT INTO municipios (departamento,nombre) VALUES (54,'VILLA DEL ROSARIO');
INSERT INTO municipios (departamento,nombre) VALUES (63,'ARMENIA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'BUENAVISTA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'CALARCA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'CIRCASIA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'CORDOBA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'FILANDIA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'GENOVA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'LA TEBAIDA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'MONTENEGRO');
INSERT INTO municipios (departamento,nombre) VALUES (63,'PIJAO');
INSERT INTO municipios (departamento,nombre) VALUES (63,'QUIMBAYA');
INSERT INTO municipios (departamento,nombre) VALUES (63,'SALENTO');
INSERT INTO municipios (departamento,nombre) VALUES (66,'PEREIRA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'APIA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'BALBOA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'BELEN DE UMBRIA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'DOSQUEBRADAS');
INSERT INTO municipios (departamento,nombre) VALUES (66,'GUATICA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'LA CELIA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'LA VIRGINIA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'MARSELLA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'MISTRATO');
INSERT INTO municipios (departamento,nombre) VALUES (66,'PUEBLO RICO');
INSERT INTO municipios (departamento,nombre) VALUES (66,'QUINCHIA');
INSERT INTO municipios (departamento,nombre) VALUES (66,'SANTA ROSA DE CABAL');
INSERT INTO municipios (departamento,nombre) VALUES (66,'SANTUARIO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BUCARAMANGA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'AGUADA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ALBANIA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ARATOCA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BARBOSA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BARICHARA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BARRANCABERMEJA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BETULIA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'BOLIVAR');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CABRERA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CALIFORNIA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CAPITANEJO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CARCASI');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CEPITA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CERRITO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CHARALA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CHARTA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CHIMA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CHIPATA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CIMITARRA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CONCEPCION');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CONFINES');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CONTRATACION');
INSERT INTO municipios (departamento,nombre) VALUES (68,'COROMORO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'CURITI');
INSERT INTO municipios (departamento,nombre) VALUES (68,'EL CARMEN DE CHUCURI');
INSERT INTO municipios (departamento,nombre) VALUES (68,'EL GUACAMAYO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'EL PEÑON');
INSERT INTO municipios (departamento,nombre) VALUES (68,'EL PLAYON');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ENCINO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ENCISO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'FLORIAN');
INSERT INTO municipios (departamento,nombre) VALUES (68,'FLORIDABLANCA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GALAN');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GAMBITA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GIRON');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GUACA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GUADALUPE');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GUAPOTA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GUAVATA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'GsEPSA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'HATO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'JESUS MARIA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'JORDAN');
INSERT INTO municipios (departamento,nombre) VALUES (68,'LA BELLEZA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'LANDAZURI');
INSERT INTO municipios (departamento,nombre) VALUES (68,'LA PAZ');
INSERT INTO municipios (departamento,nombre) VALUES (68,'LEBRIJA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'LOS SANTOS');
INSERT INTO municipios (departamento,nombre) VALUES (68,'MACARAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'MALAGA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'MATANZA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'MOGOTES');
INSERT INTO municipios (departamento,nombre) VALUES (68,'MOLAGAVITA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'OCAMONTE');
INSERT INTO municipios (departamento,nombre) VALUES (68,'OIBA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ONZAGA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PALMAR');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PALMAS DEL SOCORRO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PARAMO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PIEDECUESTA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PINCHOTE');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PUENTE NACIONAL');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PUERTO PARRA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'PUERTO WILCHES');
INSERT INTO municipios (departamento,nombre) VALUES (68,'RIONEGRO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SABANA DE TORRES');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN ANDRES');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN BENITO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN GIL');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN JOAQUIN');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN JOSE DE MIRANDA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN MIGUEL');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SAN VICENTE DE CHUCURI');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SANTA BARBARA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SANTA HELENA DEL OPON');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SIMACOTA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SOCORRO');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SUAITA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SUCRE');
INSERT INTO municipios (departamento,nombre) VALUES (68,'SURATA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'TONA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'VALLE DE SAN JOSE');
INSERT INTO municipios (departamento,nombre) VALUES (68,'VELEZ');
INSERT INTO municipios (departamento,nombre) VALUES (68,'VETAS');
INSERT INTO municipios (departamento,nombre) VALUES (68,'VILLANUEVA');
INSERT INTO municipios (departamento,nombre) VALUES (68,'ZAPATOCA');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SINCELEJO');
INSERT INTO municipios (departamento,nombre) VALUES (70,'BUENAVISTA');
INSERT INTO municipios (departamento,nombre) VALUES (70,'CAIMITO');
INSERT INTO municipios (departamento,nombre) VALUES (70,'COLOSO');
INSERT INTO municipios (departamento,nombre) VALUES (70,'COROZAL');
INSERT INTO municipios (departamento,nombre) VALUES (70,'COVEÑAS');
INSERT INTO municipios (departamento,nombre) VALUES (70,'CHALAN');
INSERT INTO municipios (departamento,nombre) VALUES (70,'EL ROBLE');
INSERT INTO municipios (departamento,nombre) VALUES (70,'GALERAS');
INSERT INTO municipios (departamento,nombre) VALUES (70,'GUARANDA');
INSERT INTO municipios (departamento,nombre) VALUES (70,'LA UNION');
INSERT INTO municipios (departamento,nombre) VALUES (70,'LOS PALMITOS');
INSERT INTO municipios (departamento,nombre) VALUES (70,'MAJAGUAL');
INSERT INTO municipios (departamento,nombre) VALUES (70,'MORROA');
INSERT INTO municipios (departamento,nombre) VALUES (70,'OVEJAS');
INSERT INTO municipios (departamento,nombre) VALUES (70,'PALMITO');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAMPUES');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN BENITO ABAD');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN JUAN DE BETULIA');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN MARCOS');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN ONOFRE');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN PEDRO');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SAN LUIS DE SINCE');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SUCRE');
INSERT INTO municipios (departamento,nombre) VALUES (70,'SANTIAGO DE TOLU');
INSERT INTO municipios (departamento,nombre) VALUES (70,'TOLU VIEJO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'IBAGUE');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ALPUJARRA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ALVARADO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'AMBALEMA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ANZOATEGUI');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ARMERO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ATACO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'CAJAMARCA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'CARMEN DE APICALA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'CASABIANCA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'CHAPARRAL');
INSERT INTO municipios (departamento,nombre) VALUES (73,'COELLO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'COYAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'CUNDAY');
INSERT INTO municipios (departamento,nombre) VALUES (73,'DOLORES');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ESPINAL');
INSERT INTO municipios (departamento,nombre) VALUES (73,'FALAN');
INSERT INTO municipios (departamento,nombre) VALUES (73,'FLANDES');
INSERT INTO municipios (departamento,nombre) VALUES (73,'FRESNO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'GUAMO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'HERVEO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'HONDA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ICONONZO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'LERIDA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'LIBANO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'MARIQUITA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'MELGAR');
INSERT INTO municipios (departamento,nombre) VALUES (73,'MURILLO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'NATAGAIMA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ORTEGA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'PALOCABILDO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'PIEDRAS');
INSERT INTO municipios (departamento,nombre) VALUES (73,'PLANADAS');
INSERT INTO municipios (departamento,nombre) VALUES (73,'PRADO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'PURIFICACION');
INSERT INTO municipios (departamento,nombre) VALUES (73,'RIOBLANCO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'RONCESVALLES');
INSERT INTO municipios (departamento,nombre) VALUES (73,'ROVIRA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'SALDAÑA');
INSERT INTO municipios (departamento,nombre) VALUES (73,'SAN ANTONIO');
INSERT INTO municipios (departamento,nombre) VALUES (73,'SAN LUIS');
INSERT INTO municipios (departamento,nombre) VALUES (73,'SANTA ISABEL');
INSERT INTO municipios (departamento,nombre) VALUES (73,'SUAREZ');
INSERT INTO municipios (departamento,nombre) VALUES (73,'VALLE DE SAN JUAN');